language: csharp
services:
  - docker
mono: none
dist: xenial
dotnet: 3.1
install:
  - cd dotnet-k8s-microservices && dotnet restore
script:
  - docker build .
  - 
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push repository/project:$TAG
  -  docker push repository/project:latest
