language: csharp
services:
  - docker
mono: none
dist: xenial
dotnet: 3.1
install:
  - cd dotnet-k8s-microservices && dotnet restore
script:
  - cd Products.API
deploy:
  - provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh $TRAVIS_TAG $DOCKER_USERNAME $DOCKER_PASSWORD
    on:
      branch: travis
