language: csharp
services:
  - docker
mono: none
dist: xenial
dotnet: 3.1
install:
  - cd dotnet-k8s-microservices && dotnet restore
script:
  - docker build .
  - docker tag mturaga/donet-k8s:$TAG mturaga/donet-k8s:latest
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mturaga/donet-k8s:$TAG
  - docker push mturaga/donet-k8s:latest
