# Docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'docker-conn'
        command: build
        dockerfile: '$(Build.SourcesDirectory)/dotnet-k8s-microservices/Dockerfile'
        arguments: '-t $(docker-repo-name):azure-devops-$(Build.BuildId)'        
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-conn'
        repository: '$(docker-repo-name)'
        command: 'push'
        tags: 'azure-devops-$(Build.BuildId)'