apiVersion: v1
kind: Service
metadata:
  name: products-api-svc
  labels:
    run: products-api
spec:
  type: NodePort
  ports:
  - nodePort: 31000 
    port: 80    
    targetPort: 80
    protocol: TCP
  selector:
    run: products-api