language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 3.1
branches:
  only:
    - travis    
before_script:
  - chmod a+x ./travis-build.sh
script:
  - "./travis-build.sh"
notifications:
  email:
    on_success: never
    on_failure: always
